### PR TITLE
Add codes for intracranial hemorrhage model

### PR DESCRIPTION
**Pull request by lassoan**
I've added infrastructure to allow adding of ICH segmentation model terms.
Since I don't have model and test data, I could not test any of these.

labels.csv file contents:

```
LabelValue,Name,SegmentedPropertyCategoryCodeSequence.CodingSchemeDesignator,SegmentedPropertyCategoryCodeSequence.CodeValue,SegmentedPropertyCategoryCodeSequence.CodeMeaning,SegmentedPropertyTypeCodeSequence.CodingSchemeDesignator,SegmentedPropertyTypeCodeSequence.CodeValue,SegmentedPropertyTypeCodeSequence.CodeMeaning,SegmentedPropertyTypeModifierCodeSequence.CodingSchemeDesignator,SegmentedPropertyTypeModifierCodeSequence.CodeValue,SegmentedPropertyTypeModifierCodeSequence.CodeMeaning,AnatomicRegionSequence.CodingSchemeDesignator,AnatomicRegionSequence.CodeValue,AnatomicRegionSequence.CodeMeaning,AnatomicRegionModifierSequence.CodingSchemeDesignator,AnatomicRegionModifierSequence.CodeValue,AnatomicRegionModifierSequence.CodeMeaning
1,Intracerebral_Haemorrhage,SCT,49755003,Morphologically Altered Structure,SCT,50960005,Hemorrhage,,,,SCT,113305005,Cerebellum,,,
2,Intraventricular_Haemorrhage,SCT,49755003,Morphologically Altered Structure,SCT,50960005,Hemorrhage,,,,SCT,279245009,Ventricular system of brain,,,
3,Subdural_Haemorrhage,SCT,49755003,Morphologically Altered Structure,SCT,50960005,Hemorrhage,,,,SCT,54214006,Subdural space,,,
4,Subarachnoid_Haemorrhage,SCT,49755003,Morphologically Altered Structure,SCT,50960005,Hemorrhage,,,,SCT,35951006,Subarachnoid space,,,
10,Brain_Parenchyma,SCT,123037004,Anatomical Structure,SCT,836432005,Parenchyma of brain,,,,,,,,,
11,Subarachnoid_Space,SCT,123037004,Anatomical Structure,SCT,35951006,Subarachnoid space,,,,,,,,,
12,Dural_Folds_Venous_Sinuses,SCT,123037004,Anatomical Structure,SCT,54944003,Dural venous sinus,,,,,,,,,
13,Septum_Pellucidum,SCT,123037004,Anatomical Structure,SCT,70146006,Septum pellucidum,,,,,,,,,
14,Cerebellum,SCT,123037004,Anatomical Structure,SCT,113305005,Cerebellum,,,,,,,,,
15,Caudate_Nucleus,SCT,123037004,Anatomical Structure,SCT,11000004,Caudate nucleus,,,,,,,,,
16,Lentiform_Nucleus,SCT,123037004,Anatomical Structure,SCT,41648007,Lentiform nucleus,,,,,,,,,
17,Insular_Cortex,SCT,123037004,Anatomical Structure,SCT,36169008,Insula,,,,,,,,,
18,Internal_Capsule,SCT,123037004,Anatomical Structure,SCT,85637007,Internal capsule,,,,,,,,,
19,Ventricular_System,SCT,123037004,Anatomical Structure,SCT,279245009,Ventricular system of brain,,,,,,,,,
20,Lobar,SCT,123037004,Anatomical Structure,SCT,???,???,,,,,,,,,
21,Thalamus,SCT,123037004,Anatomical Structure,SCT,42695009,Thalamus,,,,,,,,,
```

@diazandr3s
- I was not sure about the meaning of `dural_folds_venous_sinuses` and I have no idea what `Lobar` may mean. Could you please check?
- Could you provide the model files and test images that overall contain all segments

After these questions are answered, the changes can be finalized and merged.

### CODE REVIEW

**Comment by diazandr3s** [comment]
Hi @lassoan,

Many thanks for this.
I've uploaded the models. Let me check if I can find an image that contains all segments.
BTW, just tested the anatomy model on one sample volume in Slicer and it seems to work fine.

Please let me know if it works on your end.

**Comment by kenbutcher** [comment]
> I've added infrastructure to allow adding of ICH segmentation model terms. Since I don't have model and test data, I could not test any of these.
> 
> labels.csv file contents:
> 
> ```
> LabelValue,Name,SegmentedPropertyCategoryCodeSequence.CodingSchemeDesignator,SegmentedPropertyCategoryCodeSequence.CodeValue,SegmentedPropertyCategoryCodeSequence.CodeMeaning,SegmentedPropertyTypeCodeSequence.CodingSchemeDesignator,SegmentedPropertyTypeCodeSequence.CodeValue,SegmentedPropertyTypeCodeSequence.CodeMeaning,SegmentedPropertyTypeModifierCodeSequence.CodingSchemeDesignator,SegmentedPropertyTypeModifierCodeSequence.CodeValue,SegmentedPropertyTypeModifierCodeSequence.CodeMeaning,AnatomicRegionSequence.CodingSchemeDesignator,AnatomicRegionSequence.CodeValue,AnatomicRegionSequence.CodeMeaning,AnatomicRegionModifierSequence.CodingSchemeDesignator,AnatomicRegionModifierSequence.CodeValue,AnatomicRegionModifierSequence.CodeMeaning
> 1,Intracerebral_Haemorrhage,SCT,49755003,Morphologically Altered Structure,SCT,50960005,Hemorrhage,,,,SCT,113305005,Cerebellum,,,
> 2,Intraventricular_Haemorrhage,SCT,49755003,Morphologically Altered Structure,SCT,50960005,Hemorrhage,,,,SCT,279245009,Ventricular system of brain,,,
> 3,Subdural_Haemorrhage,SCT,49755003,Morphologically Altered Structure,SCT,50960005,Hemorrhage,,,,SCT,54214006,Subdural space,,,
> 4,Subarachnoid_Haemorrhage,SCT,49755003,Morphologically Altered Structure,SCT,50960005,Hemorrhage,,,,SCT,35951006,Subarachnoid space,,,
> 10,Brain_Parenchyma,SCT,123037004,Anatomical Structure,SCT,836432005,Parenchyma of brain,,,,,,,,,
> 11,Subarachnoid_Space,SCT,123037004,Anatomical Structure,SCT,35951006,Subarachnoid space,,,,,,,,,
> 12,Dural_Folds_Venous_Sinuses,SCT,123037004,Anatomical Structure,SCT,54944003,Dural venous sinus,,,,,,,,,
> 13,Septum_Pellucidum,SCT,123037004,Anatomical Structure,SCT,70146006,Septum pellucidum,,,,,,,,,
> 14,Cerebellum,SCT,123037004,Anatomical Structure,SCT,113305005,Cerebellum,,,,,,,,,
> 15,Caudate_Nucleus,SCT,123037004,Anatomical Structure,SCT,11000004,Caudate nucleus,,,,,,,,,
> 16,Lentiform_Nucleus,SCT,123037004,Anatomical Structure,SCT,41648007,Lentiform nucleus,,,,,,,,,
> 17,Insular_Cortex,SCT,123037004,Anatomical Structure,SCT,36169008,Insula,,,,,,,,,
> 18,Internal_Capsule,SCT,123037004,Anatomical Structure,SCT,85637007,Internal capsule,,,,,,,,,
> 19,Ventricular_System,SCT,123037004,Anatomical Structure,SCT,279245009,Ventricular system of brain,,,,,,,,,
> 20,Lobar,SCT,123037004,Anatomical Structure,SCT,???,???,,,,,,,,,
> 21,Thalamus,SCT,123037004,Anatomical Structure,SCT,42695009,Thalamus,,,,,,,,,
> ```
> 
> @diazandr3s
> 
> * I was not sure about the meaning of `dural_folds_venous_sinuses` and I have no idea what `Lobar` may mean. Could you please check?
> * Could you provide the model files and test images that overall contain all segments
> 
> After these questions are answered, the changes can be finalized and merged.

Hi Andras,

I developed this model by leveraging a tensor flow NCCT brain segmentation model I found on Github (Jason Cai).  It was trained on a small number of scans, but is remarkably accurate.  There were issues with frontal/temporal/parietal/occipital lobe boundaries, however, so I just combined them into 'lobar'.  I could just as easily combined those segments with the rather non-specific 'brain parenchyma'.  Similarly, I combined the central sulcus into subarachnoid spaces.  Dural folds were the original labels, but they refer collectively to the falx cerebri, tentorium cerebelli, falx cerebelli, and diaphragma sellae.

My goal was to see if we could improve model performance for segmentation of intraventricular, subdural and subarachnoid blood by training it on regular anatomy--what I have done is combine those labels with my Ground Truth ICrH labels.  The jury is still out on whether that was successful or not!  The truth is I really don't have enough SAH or SDH to train a model properly, but I figured it was better to start with ultimate goal in mind, rather than trying to add on additional hemorrhage types later.  I actually have two segresnet models--one is anatomy and ICrH and one is ICrH only (well four, as there are two for each). I'm not sure what Andres gave you, but I'm happy for you to publish both (or all four).  They all still need work to be honest and I am working on more challenging Ground Truth segmentations (with my students) now.

Thank you for hosting the models and please let me know if you need anything else from me.

Ken

**Comment by lassoan** [comment]
Thanks for the information @kenbutcher 

We can use [Structure of lobe of brain](https://browser.ihtsdotools.org/?perspective=full&conceptId1=90597002&edition=MAIN/2024-04-01&release=&languages=en) for `lobar`, unless you think we should use one of the more specific children instead: "Cerebellar lobe structure" or "Cerebral lobe structure". It would make sense to change the "Lobar" internal name to something like "Brain_Lobe".

> I combined the central sulcus into subarachnoid spaces. Dural folds were the original labels, but they refer collectively to the falx cerebri, tentorium cerebelli, falx cerebelli, and diaphragma sellae.

The proper SNOMED term for this seems to be [Dura mater structure](https://browser.ihtsdotools.org/?perspective=full&conceptId1=18545000&edition=MAIN/2024-04-01&release=&languages=en).
Accordingly, internal name should be probably changed from "Dural_Folds_Venous_Sinuses" to "Dura_Mater".

**Comment by lassoan** [comment]
Thank you! Where is this image from? (I would add it to the test data sets and it is good if we can indicate the source)

**Comment by diazandr3s** [comment]
It is part of the dataset curated by @kenbutcher.
@kenbutcher can you please comment on this?

**Comment by kenbutcher** [comment]
> Thanks for the information @kenbutcher
> 
> We can use [Structure of lobe of brain](https://browser.ihtsdotools.org/?perspective=full&conceptId1=90597002&edition=MAIN/2024-04-01&release=&languages=en) for `lobar`, unless you think we should use one of the more specific children instead: "Cerebellar lobe structure" or "Cerebral lobe structure". It would make sense to change the "Lobar" internal name to something like "Brain_Lobe".
> 
> > I combined the central sulcus into subarachnoid spaces. Dural folds were the original labels, but they refer collectively to the falx cerebri, tentorium cerebelli, falx cerebelli, and diaphragma sellae.
> 
> The proper SNOMED term for this seems to be [Dura mater structure](https://browser.ihtsdotools.org/?perspective=full&conceptId1=18545000&edition=MAIN/2024-04-01&release=&languages=en). Accordingly, internal name should be probably changed from "Dural_Folds_Venous_Sinuses" to "Dura_Mater".

I think 'Cerebral Lobes' would be most accurate, but I don't know my snomed codes, so if 'Structure of Lobe of the Brain' is the code, that's fine (although it seems a bit unwieldy!).  Dura_Mater is fine too (although technically that includes more than those areas segmented by the model).

**Pull request merged**
