### PR TITLE
Add whole body CT segmentation model

### PR DESCRIPTION
**Pull request by diazandr3s**

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
Looks good, thank you. I'll add sample data to the description later.

**Comment by lassoan** [comment]
The model works very nicely. It would be great if you could train a fast (low-resolution) version as well!

**Comment by lassoan** [comment]
It is a bit odd that the brains shows up in the liver:

image

**Comment by diazandr3s** [comment]
Thanks for feedback, @lassoan.
I'm working on improving the model and adding a low-res one.

**Comment by lassoan** [comment]
Great, thank you!

**Pull request merged**
